NVIDIA/dcgm-exporter

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
service-monitor.yaml

Signed-off-by: Douglas Wightman <dwightman@nvidia.com>

Bump exporter to verison 2.5.0

---

Makefile

Signed-off-by: Nik Konyuchenko <spaun2002mobile@gmail.com>

Properly update BuildVersion in the Makefile

---

go.mod
go.sum
pkg/dcgmexporter/kubernetes.go
pkg/dcgmexporter/kubernetes_test.go
pkg/dcgmexporter/pipeline.go
pkg/dcgmexporter/system_info.go

Signed-off-by: Douglas Wightman <dwightman@nvidia.com>

Use go-nvml to parse MIG device details

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
service-monitor.yaml

2.6.1 - use go-nvml to parse MIG device details

Version bump to 2.6.1

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
service-monitor.yaml

Signed-off-by: Douglas Wightman <dwightman@nvidia.com>

Bump version to 2.3.2-2.6.2

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/templates/daemonset.yaml
deployment/values.yaml
service-monitor.yaml

Also fix small syntax error in daemonset.yaml
Signed-off-by: Douglas Wightman <dwightman@nvidia.com>

Bump version to 2.3.4-2.6.4

---

deployment/templates/NOTES.txt
deployment/templates/_helpers.tpl
deployment/templates/daemonset.yaml
deployment/templates/metrics-configmap.yaml
deployment/templates/role.yaml
deployment/templates/rolebinding.yaml
deployment/templates/service-monitor.yaml
deployment/templates/service.yaml
deployment/templates/serviceaccount.yaml
deployment/values.yaml

add namespace override for multi-namespace deployments in combined charts
https://github.com/helm/charts/pull/15202

feat: add namespace override for multi-namespace deployments

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
go.mod
go.sum
service-monitor.yaml

Update go-dcgm bindings to address API mismatch error

Bump version to 2.4.6-2.6.9

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
go.mod
go.sum
grafana/dcgm-exporter-dashboard.json
service-monitor.yaml

* Update DCGM to 3.0.4
* Update headers to 3.0.4

Bump version to 3.0.4-3.0.0

---

README.md

Signed-off-by: Bruce Merry <bmerry@sarao.ac.za>

Fix link to field identifiers

---

pkg/dcgmexporter/pipeline.go

Signed-off-by: Bruce Merry <bmerry@sarao.ac.za>

Fix a typo in an error message

---

pkg/dcgmexporter/parser.go

Fixes: #118
Signed-off-by: LetFu <letfu@outlook.com>

fix: convert config map without removing comments

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
docker/Dockerfile.ubi8
docker/Dockerfile.ubuntu20.04
pkg/dcgmexporter/system_info.go
service-monitor.yaml

Includes one bug fix for selecting specific nvswitches

Update to DCGM 3.1.3

---

deployment/templates/daemonset.yaml
pkg/dcgmexporter/gpu_collector.go

Signed-off-by: Shiva Krishna, Merla <smerla@nvidia.com>

Use NODE_NAME env instead of hostname (which is podname) for the metrics

---

grafana/dcgm-exporter-dashboard.json

Signed-off-by: Doron Kedem Goldman <doronkg@gmail.com>

Align framebuffer panel legend

---

pkg/dcgmexporter/pipeline.go

links and switches are not available within pods

Issue 133 - remove kubernetes transforms for links and switches

---

grafana/dcgm-exporter-dashboard.json

* Fixed variable injection into targets
* Fixed funtion arguments for the `gpu` label templating

Fix Grafana dashboard

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
go.mod
go.sum
service-monitor.yaml

- Update DCGM to 3.2.5
- Grafana fix

Bump version to 3.2.5-3.1.7

---

Makefile
README.md
dcgm-exporter.yaml
deployment/Chart.yaml
deployment/values.yaml
service-monitor.yaml

- Incorporate latest community MRs

Bump version to 3.2.5-3.1.8

---

docker/Dockerfile.ubi8
docker/Dockerfile.ubuntu20.04

Removed unnecessary artifacts and reduced the number of layers to reduce image size from ~2GB to 1.45GB (Ubuntu) and 1.62GB (UBI).

Removed unnecessary artifacts and reduced the number of layers

---

go.mod
go.sum
pkg/dcgmexporter/gpu_collector_test.go
pkg/dcgmexporter/pipeline.go
pkg/dcgmexporter/system_info.go

Fix for monitoring cpu cores

---

pkg/dcgmexporter/gpu_collector.go

Fix to ignore entities when no applicable fields selected

---

pkg/dcgmexporter/gpu_collector.go
pkg/dcgmexporter/gpu_collector_test.go
pkg/dcgmexporter/test_utils.go
pkg/dcgmexporter/xid_collector_test.go

Bug fix for the issue #250 dcgm-exporter on main does not report metrics for all GPUs.

The issue "250 dcgm-exporter on main does not report metrics for all GPUs"

---

.vscode/launch.json
docker/Dockerfile.ubi9
go.mod
pkg/cmd/app.go
pkg/dcgmexporter/const.go
pkg/dcgmexporter/dcgm.go
pkg/dcgmexporter/gpu_collector.go
pkg/dcgmexporter/kubernetes.go
pkg/dcgmexporter/kubernetes_test.go
pkg/dcgmexporter/pipeline.go
pkg/dcgmexporter/pipeline_test.go
pkg/dcgmexporter/server.go
pkg/dcgmexporter/system_info.go
pkg/dcgmexporter/system_info_test.go
pkg/dcgmexporter/types.go
pkg/dcgmexporter/xid_collector.go
pkg/dcgmexporter/xid_collector_test.go
tests/integration/start_read_test.go
tests/integration/start_with_tls_test.go

The following issues in the code were resolved:
1. Ignored errors;
2. Code contains unused structs;
3. Some variables don't follow the GOlang naming conventions;
4. Incorrect conditions like: `len(sysInfo.cOpt.MajorRange) <= 0` that causes a functional defects;
5. Loops are unconditionally terminated;
6. Use the deprecated packages and methods.
Also:
1. New unit tests added to increase code coverage by tests;
2. Add a new "--debug" parameter that allows users to see debug messages, which helps to improve troubleshooting.

Resolved linter-identified issues for improved code quality

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Makefile

The PR adds a containerized development environment for the dcgm-exporter. 
You can read about dev containers here: https://devcontainers.github.io/

Added devcontainer

---

.gitignore
Makefile

Added: make test-coverage to show the current test coverage

Added: make test-coverage to show the current test coverage

---

deployment/Chart.yaml
deployment/templates/service-monitor.yaml
deployment/values.yaml

Allows the service monitor API to be configurable for other providers

Service monitor API value configurable

---

dcgm-exporter.yaml

Issue: https://github.com/NVIDIA/dcgm-exporter/issues/402

Maintain uniformity with helm chart and static yaml's by adding securityContext

---

deployment/templates/service-monitor.yaml

Issue: https://github.com/NVIDIA/dcgm-exporter/issues/405

Fix Helm Templates Generation

---

deployment/templates/service-monitor.yaml

[Helm] remove extra line

---

deployment/templates/daemonset.yaml

Feat: Allow specifying an initcontainer on the daemonset
