- deployment/templates/service.yaml
- deployment/values.yaml
We scrape the pod port directly. Plus scraping the service doesn't really work with daemonset since the service will point to only one of the daemonset pods, and when more than one node exists with GPUs, this ends up not scraping more than one node.
> Allow disabling service

- deployment/templates/daemonset.yaml
- deployment/values.yaml
This is useful when using Prometheus but not with an operator so can tell Prometheus to scrape the pod port.
> Allow pod annotations for the daemonset

- deployment/templates/metrics-configmap.yaml
- deployment/templates/role.yaml
- deployment/templates/rolebinding.yaml
fix: add role to read the cm 
```
Could not retrieve ConfigMap 'monitoring:exporter-metrics-volume': configmaps \"exporter-metrics-volume\" is forbidden:
User \"system:serviceaccount:monitoring:dcgm-exporter\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"monitoring\", falling back to metric file /etc/dcgm-exporter/dcp-metrics-included.csv
```
Signed-off-by: Cyril Corbon <corboncyril@gmail.com>
> fix: add role to read the cm

- docker/dcgm-exporter-entrypoint.sh
The warnings are never printed because the script uses 'set -e'. Please consider either cleaning up by deleting the unused code or fixing it to work as intended (this MR).
Before:
```
$ enroot start nvidia+k8s+dcgm-exporter+2.3.4-2.6.4-ubuntu20.04
unable to set CAP_SETFCAP effective capability: Operation not permitted
$ echo $?
1
```
After:
```
$ enroot start nvidia+k8s+dcgm-exporter+2.3.4-2.6.4-ubuntu20.04
unable to set CAP_SETFCAP effective capability: Operation not permitted
Warning #1: dcgm-exporter doesn't have sufficient privileges to expose profiling metrics. To get profiling metrics with dcgm-exporter, use --cap-add SYS_ADMIN
INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Collecting DCP Metrics
INFO[0000] No configmap data specified, falling …
```
> Fix setcap check in docker entrypoint

- README.md
- deployment/templates/metrics-configmap.yaml
- etc/1.x-compatibility-metrics.csv
- etc/dcp-metrics-included.csv
- etc/default-counters.csv
- pkg/dcgmexporter/parser.go
Also remove the check for empty lines because encoding/csv's parser already does this automatically.
> Don't require csv comments to have 2 commas

- deployment/templates/daemonset.yaml
If hostNetwork parameter is set to `true`  then host ip is assigned to the daemonset instead of assigning a new ip.
This can be set to true, when:
- Daemonset is not externallly accessed.
- It saves an Ip address.
If `hostNetwork` is available  in values yaml. and value is 'true' then add the hostNetwork parameter to template spec.
spec:
{{- if .Values.hostNetwork }}
hostNetwork: {{ .Values.hostNetwork }}
{{- end }}
Signed-off-by: Vasudev Singh C <vasudev.singhc@jda.com>
> [add]: support for `hostNetwork` parameter in daemonset deployment

- deployment/templates/daemonset.yaml
- deployment/values.yaml
Failed to add annotation by using helm tool
Reason: it's missing podAnnotations values in annotation block at template spec
Purpose:
- using this annotation that is required for prometheus scraping
In values.yml should be
```
podAnnotations:
prometheus.io/scrape: "true"
prometheus.io/port: "9400"
```
> #fixed: failed to add annotations

- deployment/templates/service-monitor.yaml
- deployment/values.yaml
By default, if metrics are scraped by Prometheus, there will be label conflicts with the labels `container`, `namespace` and `pod`. This is because honor label config when unset defaults to `false`. Label conflicts are resolved by renaming conflicting labels in the scraped data to "exported_<original-label>".
This PR allows specifying `honorLabels` in the endpoint specification of ServiceMonitor. When this field is set `true`, label conflicts are resolved by keeping label values from the scraped data. 
Signed-off-by: Chris Sng <chrissng@users.noreply.github.com>
> Allow specifying honorLabels in ServiceMonitor spec

- cmd/dcgm-exporter/main.go
- go.mod
- go.sum
- pkg/dcgmexporter/parser.go
- pkg/dcgmexporter/types.go
Before:
```
INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Collecting DCP Metrics
INFO[0000] No configmap data specified, falling back to metric file etc/dcgm-exporter/dcp-metrics-included.csv
FATA[0001] Error watching fields: Feature not supported
```
Now:
```
dcgm-exporter -f etc/dcgm-exporter/dcp-metrics-included.csv
INFO[0000] Starting dcgm-exporter
INFO[0000] DCGM successfully initialized!
INFO[0000] Collecting DCP Metrics
INFO[0000] No configmap data specified, falling back to metric file etc/dcgm-exporter/dcp-metrics-included.csv
WARN[0000] Skipping line 24 ('DCGM_FI_PROF_PIPE_TENSOR_IMMA_ACTIVE'): metric not enabled
WARN[0000] Skipping line 25 ('DCGM_FI_PROF_PIPE_TENSOR_HMMA_ACTIVE'): metric not enabled
INFO[0001] Starting webserver …
```
> 82 - query supported metric groups and skip unsupported

- etc/dcp-metrics-included.csv
DCGM_FI_PROF_PCIE_TX_BYTES and DCGM_FI_PROF_PCIE_RX_BYTES are PCIe bandwidths that are computed for each scraping interval. The types of those metrics were mistakenly specified as 'counter' instead of 'gauge.' 
The descriptions of those metrics were also updated according to the official DCGM documentation.The descriptions of those metrics were also updated according to the officidal DCGM documentation.
> Fix the type of the PCIE_TX/RX metrics and provide more accurate description.

- etc/dcp-metrics-included.csv
- etc/default-counters.csv
- pkg/dcgmexporter/gpu_collector.go
- pkg/dcgmexporter/gpu_collector_test.go
- pkg/dcgmexporter/pipeline.go
- pkg/dcgmexporter/types.go
Any entry in the config file with type "label" will become a label on
all metrics.
Closes https://github.com/NVIDIA/dcgm-exporter/issues/72.
> Add support for string fields as labels

- go.mod
- go.sum
- pkg/dcgmexporter/gpu_collector.go
- pkg/dcgmexporter/pipeline.go
Rather than try to reconnect, simply fail and let controller (k8s, etc) determine whether to restart or not.
> Exit if the hostengine connection goes down

- Makefile
- go.mod
- go.sum
- pkg/dcgmexporter/pipeline.go
DCGM_FI_DEV_NVSWITCH_LINK_STATUS can now be used to query nvlink state.
> Update go bindings, remove nvlink status workaround

- grafana/dcgm-exporter-dashboard.json
Make this an "instant" query, that is, calculate the sum over the latest values only (the values listed under "current" in the GPU Power Usage panel to the left)
Previously, it would sum all the values in the range, resulting in an absurdly high value (which could perhaps be scaled to kWh, but is definitly not W any more)
See
https://grafana.com/grafana/dashboards/12239-nvidia-dcgm-exporter-dashboard/?tab=reviews for at least three comments hinting at this problem.
> Grafana dashboard: fix GPU Power Total

- deployment/values.yaml
This setting isn't used and led to some initial confusion while I was configuring this helm chart. Cheers!
> Remove unused mapPodMetrics helm chart setting

- etc/default-counters.csv
Bring these in line with [their official docs](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html#c.DCGM_FI_DEV_FB_FREE)
> fix frame buffer field descriptions default-counters.csv

- deployment/templates/daemonset.yaml
- deployment/values.yaml
Hello! 
I've added parameters to Daemonset rollingupdate strategy, which will help to faster update DCGM exporter installation inside k8s cluster with a lot of nodes.
Default values are taken from default [Daemonset spec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec), so it's backward-compatible too.
> Add ability to change default rollingupdate parameters in helm chart

- go.mod
This fixes the following build failure when using vendored dependencies:
$ go mod vendor
$ make binary
cd cmd/dcgm-exporter; go build -ldflags "-X
main.BuildVersion=3.1.8-3.1.5"
../../vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../../vendor/golang.org/x/sys/unix/syscall_linux.go:1018:20: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../../vendor/golang.org/x/sys/unix/syscall_linux.go:2289:9: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../../vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../../vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: unsafe.Slice …
> Update go.mod go version to 1.17

- deployment/templates/daemonset.yaml
- deployment/values.yaml
Hi,
A tiny PR to be able to force the `runtimeClassName` when I'm not using by default `nvidia` in my CRI config.
Thanks
> chore: allow override runtimeClassName

- pkg/dcgmexporter/kubernetes.go
This PR adds k8s resources metrics like `pod`, `namespace`, and `container` to GPU metrics extracted by DCGM in GPU virtualized environments. Attributing GPU metrics to containers or virtual machines can be tricky when the GPU is shared but here the argument is that these metrics are by virtue of those containers using the GPU. Implementation-wise, the main assumption is that in virtualized environments the `deviceId` used by a container takes the form of `{device-name/uid}/vgpu{number}` and this needs to be mapped to metrics appropriately. The PR has been tested with NVIDIA T4 GPU on a GKE cluster with [time sharing](https://cloud.google.com/kubernetes-engine/docs/concepts/timesharing-gpus) enabled.
Possibly related to 
- https://github.com/NVIDIA/dcgm-exporter/issues/144
- …
> Support for k8s labelled metrics with gpu virtualization or time sharing

- pkg/dcgmexporter/kubernetes.go
This PR addresses https://github.com/NVIDIA/dcgm-exporter/issues/144 and fixes the issue of incorrect `deviceid` being used as the key when `podInfo` is added, in the case when the device is time-slicing GPU. As a result, empty attributes are assigned to the metrics.  
A similar [PR](https://github.com/NVIDIA/dcgm-exporter/pull/185) has already been raised but it only addresses the issue when the cloud provider is GKE. The `deviceid` of time-slicing GPU of AWS takes the form of `{gpuInstanceId}::{number}`.
> fix: device attribute of time-slicing gpu metrics

- deployment/templates/daemonset.yaml
- deployment/values.yaml
Hello!
I've added the parameter to allow users to supply additional pod labels, complementing the existing ones. This can help user control over deployments, improve monitoring, and assist in both organization and policy definition based on pod labels.
Please share any concerns or feedback you might have regarding this change!
> Support supplying custom pod labels

- Makefile
557 seems like a dangerous permission string for these files, maybe 755 and 644 would be better?
> Update Install Perms in Makefile

- pkg/dcgmexporter/gpu_collector_test.go
- pkg/dcgmexporter/system_info.go
A few unit tests could be run on a machine with specific hardware. The reason for the failure is dependency on hardware. 
I used [hooking](https://en.wikipedia.org/wiki/Hooking) technology to add an abstraction layer between `dcgm-exporter` and the dcgm library. When creating a unit test, we can use mocks to emulate a dcgm behavior during various scenarios.
> Broken unit tests were fixed

- pkg/cmd/app.go
- pkg/dcgmexporter/gpu_collector.go
- pkg/dcgmexporter/pipeline.go
- pkg/dcgmexporter/pipeline_test.go
cleanup is shadowed by the later ones, especially the GPU Collector cleanup, which never has a chance to be executed.
this may be related to https://github.com/NVIDIA/dcgm-exporter/issues/215
> Fix cleanup leak in pipeline collectors

- go.mod
- go.sum
- internal/README.md
- internal/pkg/nvmlprovider/provider.go
- internal/pkg/nvmlprovider/provider_test.go
- internal/pkg/testutils/testutils.go
- pkg/dcgmexporter/kubernetes.go
- pkg/dcgmexporter/kubernetes_test.go
The owner archived the dependency github.com/NVIDIA/gpu-monitoring-tools on Nov 2, 2021. 
The `go-nvml` package replaced the obsolete dependency.  
Unit tests were added to cover the mapping of metrics on pods.
> Dependency from obsolete package was removed

- pkg/cmd/app.go
- pkg/dcgmexporter/gpu_collector.go
- pkg/dcgmexporter/gpu_collector_test.go
- pkg/dcgmexporter/types.go
**Problem:** [NVIDIA/k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) produces K8S labels `gpu.product` values with blank spaces replaced with dash. 
The dcgm-exporter reads the GPU model name from DCGM, doesn't perform blank space replacement with dashes, and returns raw values as the DCGM library returns. This leads to a mismatch between the GPU product name on the Kubernetes node label and the one in the DCGM metrics. For example:
The label has the value: "nvidia.com/gpu.product" = "NVIDIA-T400-4GB" on a node label, but in DCGM metric, it is called: "NVIDIA T400 4GB".
**Solution**
Added the new "replace-blanks-in-model-name" parameter, that asks DCGM-Exporter to replace every blank space in the GPU model name with a dash, ensuring a continuous, space-free identifier. …
> Added new command line parameter: replace-blanks-in-model-name

- .gitignore
- internal/pkg/nvmlprovider/provider.go
- pkg/cmd/app.go
- pkg/dcgmexporter/const.go
- pkg/dcgmexporter/const_test.go
- pkg/dcgmexporter/dcgm.go
- pkg/dcgmexporter/gpu_collector.go
- pkg/dcgmexporter/kubernetes.go
- pkg/dcgmexporter/kubernetes_test.go
- pkg/dcgmexporter/parser.go
- pkg/dcgmexporter/pipeline.go
- pkg/dcgmexporter/pipeline_test.go
- pkg/dcgmexporter/server.go
- pkg/dcgmexporter/system_info.go
- pkg/dcgmexporter/system_info_test.go
- pkg/dcgmexporter/utils.go
- pkg/dcgmexporter/xid_collector.go
The purpose of this PR is to achieve consistent error message styling. Styling follows the following conventions:
1. Error strings should not be capitalized (unless beginning with an exported name, a proper noun or an acronym) and should not end with punctuation. 
```
err := fmt.Errorf("something bad happened")
```
2. Error message is separated from the main message string using `;` seperator.
```
err := fmt.Errorf("something bad happened; err: %w", err)
```
3. Use of `%w` in place of `%v` to make it available to `errors.Is` and `errors.As` when supporting custom errors in future.
**NOTE:** There were 2-3 instances where it was not possible to applying the correct styling without changing existing logic a bit. So please pay special attention to those changes.
> Make error message styling consistent

- etc/default-counters.csv
- pkg/cmd/app.go
- pkg/dcgmexporter/clock_events_collector.go
- pkg/dcgmexporter/clock_events_collector_test.go
- pkg/dcgmexporter/config.go
- pkg/dcgmexporter/exporter_metrics.go
The new metric DCGM_FI_EXP_CLOCK_THROTTLE_REASONS_COUNT was renamed to the DCGM_EXP_CLOCK_EVENTS_COUNT. 
Metric output:
```
DCGM_EXP_CLOCK_EVENTS_COUNT{gpu="0",UUID="GPU-b9f9e81b-bee7-34bc-af17-132ef6592740",device="nvidia0",modelName="NVIDIA T400 4GB",Hostname="home",DCGM_FI_DRIVER_VERSION="545.29.02",clock_event="gpu_idle",window_size_in_ms="300000"} 2
DCGM_EXP_CLOCK_EVENTS_COUNT{gpu="0",UUID="GPU-b9f9e81b-bee7-34bc-af17-132ef6592740",device="nvidia0",modelName="NVIDIA T400 4GB",Hostname="home",DCGM_FI_DRIVER_VERSION="545.29.02",clock_event="sw_thermal",window_size_in_ms="300000"} 1
DCGM_EXP_CLOCK_EVENTS_COUNT{gpu="0",UUID="GPU-b9f9e81b-bee7-34bc-af17-132ef6592740",device="nvidia0",modelName="NVIDIA T400 4GB",Hostname="home",DCGM_FI_DRIVER_VERSION="545.29.02",clock_event="hw_thermal",win …
```
> DCGM_FI_EXP_CLOCK_THROTTLE_REASONS_COUNT was renamed to the DCGM_EXP_CLOCK_EVENTS_COUNT

- pkg/dcgmexporter/clock_events_collector_test.go
- pkg/dcgmexporter/expcollector.go
Fixed defect: dcgm-exporter fails into a panic when both DCGM_EXP_CL…OCK_EVENTS_COUNT and DCGM_EXP_XID_ERRORS_COUNT metrics enabled
> Fixed defect: dcgm-exporter fails into a panic

- .vscode/launch.json
- Makefile
- go.mod
- internal/pkg/logging/logger_adapter.go
- internal/pkg/logging/logger_adapter_test.go
- pkg/cmd/app.go
- pkg/dcgmexporter/config.go
- pkg/dcgmexporter/const.go
- pkg/dcgmexporter/server.go
- pkg/stdout/capture.go
- pkg/stdout/capture_test.go
- pkg/stdout/capture_test_wrapper.go
- pkg/stdout/stdoutprocessor.go
Users are now able to use the "--enable-dcgm-log" and "--dcgm-log-level=[NONE,FATAL,ERROR,WARN,INFO,DEBUG,VERB]" flags to enable DCGM library log output into the dcgm-exporter logs. 
**Important:** The default value for the "--dcgm-log-level" is "NONE". To see DCGM logs, you must set at least the `INFO` log level.
Here is an example of the DCGM log output:
```
time="2024-03-01T14:24:35-06:00" level=info msg="version:3.3.3;arch:x86_64;buildtype:Release;buildid:11;builddate:2024-01-18;commit:c3aed64480553cd5ba1a32d165c7967936446631;branch:rel_dcgm_3_3;buildplatform:Linux 4.15.0-180-generic #189-Ubuntu SMP Wed May 18 14:13:57 UTC 2022 x86_64;;crc:39ff792f5514bdc5af56ce313a8fa90e [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgmlib/src/DcgmApi.cpp:5012] [{anonymous}::StartEmbeddedV2]" …
```
> Added ability to enable DCGM library log output

- pkg/dcgmexporter/clock_events_collector_test.go
- pkg/dcgmexporter/kubernetes.go
- pkg/dcgmexporter/kubernetes_test.go
- pkg/dcgmexporter/pipeline.go
- pkg/dcgmexporter/utils_test.go
The new test case was added to capture the use case when the GPU was configured to operate in MIG mode.
> Issue-272: Added tests for K8S use case, when MIG enabled in a mixed mode

- cmd/dcgm-exporter/main.go
- go.mod
- go.sum
Go is not cgroup aware and by default will set GOMAXPROCS to the number of available threads, regardless of whether it is within the allocated quota. This behaviour causes high amount of CPU throttling and degraded application performance.
Fixes: #265
> chore: use Linux container CPU quota

- deployment/values.yaml
No changes in the values.yaml, except comments added for better documentation. 
Test steps:
1. Install K3S
```
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -
```
2. View available run times:
```
kubectl get runtimeclasses
```
You should expect to see: 
```
NAME                  HANDLER               AGE
crun                  crun                  4h
lunatic               lunatic               4h
nvidia-experimental   nvidia-experimental   4h
slight                slight                4h
spin                  spin                  4h
wasmedge              wasmedge              4h
wasmer                wasmer                4h
wasmtime              wasmtime              4h
wws                   wws                   4h
nvidia                nvidia                4h
```
3. …
> Issue 102 - Allow setting runtimeClassName

- cmd/dcgm-exporter/main.go
- pkg/cmd/app.go
- pkg/dcgmexporter/clock_events_collector_test.go
- pkg/dcgmexporter/config.go
- pkg/dcgmexporter/kubernetes.go
- pkg/dcgmexporter/kubernetes_test.go
The PR adds a new command-line parameter, "pod-resources-kubelet-socket," and a new environment variable, "DCGM_POD_RESOURCES_KUBELET_SOCKET." This will help specify a custom socket path when we mount the socket in the docker container.
> make kubelet pod-resources socket directory configurable

- .vscode/launch.json
- tests/e2e/Makefile
- tests/e2e/e2e_suite_test.go
- tests/e2e/internal/framework/kube.go
- tests/e2e/main_test.go
The E2E tests with default configuration use the helm release, which deploys the dcgm-exporter with the `dcp-metrics-included.csv` configuration. This configuration includes profiling metrics available on the datacenter-grade GPU.  
For example, if you use `NVIDIA T400`, the e2e test fails because the dcgm-exporter can not be initiated because of unsupported hardware. 
To provide the ability to run e2e tests on low-grade GPUs compatible with DCGM, I added the ability to specify custom arguments in the e2e scripts. As a result:
1. The default `make e2e` command runs e2e tests with enabled profiling metrics.
2. If the developer wants to run the e2e tests without profiling metrics, they can do the following:
```
cd tests/e2e
make e2e-test-no-profiling
```
> E2E tests can be run with default-counters.csv

- .github/ISSUE_TEMPLATE/bug_report_form.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request_form.yml
- .github/ISSUE_TEMPLATE/submit-question.yml
Added new Github forms:
* Bug Report: [preview](https://github.com/NVIDIA/dcgm-exporter/blob/new-issue-forms/.github/ISSUE_TEMPLATE/bug_report_form.yml)
*  Feature Request: [preview](https://github.com/NVIDIA/dcgm-exporter/blob/new-issue-forms/.github/ISSUE_TEMPLATE/feature_request_form.yml)
* Question: [preview](https://github.com/NVIDIA/dcgm-exporter/blob/new-issue-forms/.github/ISSUE_TEMPLATE/submit-question.yml)
> Added new forms for bug, feature and question

- .vscode/launch.json
- go.mod
- go.sum
- tests/e2e/Makefile
- tests/e2e/e2e_actions_test.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/internal/framework/helm.go
- tests/e2e/internal/framework/kube.go
- tests/e2e/main_test.go
To increase the stability and extensibility of the e2e tests, the e2e tests were refactored to use the ginkgo testing framework.
> E2E use ginkgo

- .golangci.yml
- Makefile
- pkg/dcgmexporter/kubernetes_test.go
- We need to have the ability to control golangci-lint execution timeout.
- Added explicit golangci-lint configuration.
- The golangci-lint now enforces rules only in a new code. 
- Formated the file that was in the past not formatted.
> Chore: Added golangci configuration and formater to the makefile

- pkg/dcgmexporter/expcollector.go
- pkg/dcgmexporter/gpu_collector.go
- pkg/dcgmexporter/gpu_collector_test.go
- pkg/dcgmexporter/pipeline.go
- pkg/dcgmexporter/types.go
- pkg/dcgmexporter/xid_collector_test.go
This PR add `pci_bus_id` label for metrics to indicate the PCI Bus ID of the GPU.
Currently we have UUID for users to indicate a GPU card. For many reasons, you may also want to locate a GPU by its PCI Bus ID. 
For example, for cloud service providers, they supply GPU cards from the bare metal machines to Virtual Machines. However, GPU UUID is only aware to Guest system, therefore the cloud provider is unable to accurately tell the user that which GPU is broken. What the cloud provider have is only the PCI Bus ID.
Once added the `pci_bus_id` label, users can filter metrics by the Bus ID sent by the cloud provider, and receive alarms if their important tasks are affected.
> feat: add pci_bus_id label for metrics

- deployment/templates/metrics-configmap.yaml
- etc/dcp-metrics-included.csv
A few of the profiling metric gauges claimed a % unit in the help text of the sample CSVs. However, they are reported as a ratio [0,1].
This change removes the percentage unit described for correctness.
> fix: correct metric help text

- deployment/templates/metrics-configmap.yaml
- etc/1.x-compatibility-metrics.csv
- etc/dcp-metrics-included.csv
- etc/default-counters.csv
Closes #354 
This PR updates the default PCIe metric from `DCGM_FI_DEV_PCIE_{TX,RX}_THROUGHPUT` to `DCGM_FI_PROF_PCIE_{TX,RX}_BYTES` in `./etc` files to align with the DCGM Documentation (Version 3.3).
According to the DCGM Documentation, `DCGM_FI_DEV_PCIE_{TX,RX}_THROUGHPUT` is deprecated and should be replaced with `DCGM_FI_PROF_PCIE_{TX,RX}_BYTES`. This change resolves issues reported in [Issue #167](https://github.com/NVIDIA/dcgm-exporter/issues/167).
- Replaced `DCGM_FI_DEV_PCIE_{TX,RX}_THROUGHPUT` with `DCGM_FI_PROF_PCIE_{TX,RX}_BYTES` in `./etc/default-counters.csv`.
- [DCGM Documentation - DCGM API Field IDs](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/dcgm-api-field-ids.html#c.DCGM_FI_DEV_PCIE_TX_THROUGHPUT)
- [Issue #167 - Get DCGM_FI_DEV_PCIE_TX_THROUGHPUT metric …
> Rename default PCIe metrics for better readability

- pkg/cmd/app.go
- pkg/dcgmexporter/config.go
- pkg/dcgmexporter/kubernetes.go
- pkg/dcgmexporter/kubernetes_test.go
fix issue https://github.com/NVIDIA/dcgm-exporter/issues/314 , to make nvidia resource names configurable.
It can solve the problem that nvidia/k8s-device-plugin advertise specified GPU type like nvidia.com/a100 or nvidia.com/a10 and so on, not nvidia.com/gpu.
> Make nvidia resource names configurable

- README.md
- deployment/templates/metrics-configmap.yaml
- deployment/values.yaml
Closes #170 
This PR allows users to define their own custom metrics CSV in the Helm chart and mounts and consumes the ConfigMap (which was previously deployed but unused) by default. It incorporates changes originally made in PR #350.
After this PR, users may define custom metrics in the values file as the following:
```yaml
customMetrics: |-
DCGM_FI_PROF_SM_ACTIVE,          gauge, The ratio of cycles an SM has at least 1 warp assigned.
DCGM_FI_PROF_SM_OCCUPANCY,       gauge, The ratio of number of warps resident on an SM.
```
This `customMetrics` value is commented out by default to allow for backwards compatibility.
> [Helm] Enable custom metrics, mount ConfigMap by default

- deployment/templates/service.yaml
- deployment/values.yaml
This is mostly useful to be able to set it to "None", creating a headless service that can be scraped using DNS discovery (dns_sd_configs).
No change in default behavior.
> Allow selecting the service's ClusterIP

- deployment/templates/service.yaml
```
clusterIP:
```
Should only show up in manifest if `.Values.service.clusterIP` is defined. Otherwise it shows an empty value, which causes argoCD to report app as out of sync because of expects `spec.clusterIP` to have the auto assigned IP but manifest states it should be null value.
> Fix empty clusterIP when no clusterIP is defined in values

- README.md
When starting without --cap-add SYS_ADMIN, an error message is displayed prompting to add the SYS_ADMIN capability. Therefore, I updated the instructions in the README to align with this requirement.
```
$ docker run --gpus all --rm -p 9400:9400 nvcr.io/nvidia/k8s/dcgm-exporter:3.3.9-3.6.1-ubuntu22.04
Warning #2: dcgm-exporter doesn't have sufficient privileges to expose profiling metrics. To get profiling metrics with dcgm-exporter, use --cap-add SYS_ADMIN
2024/11/30 07:41:50 maxprocs: Leaving GOMAXPROCS=9: CPU quota undefined
time="2024-11-30T07:41:50Z" level=info msg="Starting dcgm-exporter"
time="2024-11-30T07:41:51Z" level=info msg="DCGM successfully initialized!"
time="2024-11-30T07:41:51Z" level=info msg="Collecting DCP Metrics"
time="2024-11-30T07:41:51Z" level=info msg="Falling …
```
> Add SYS_ADMIN capability requirement for docker run

- internal/pkg/transformation/kubernetes.go
- internal/pkg/transformation/kubernetes_test.go
We make a small fix to the Kubernetes PodMapper tranform processor.
Specifically we update the regular expression used in building the device mapping to properly capture pod attributes in both MIG and [MIG-with-sharing](https://cloud.google.com/kubernetes-engine/docs/how-to/timesharing-gpus#use-with-multi-instance-gpu) GPUs in GKE.
> fix: enable pod attributes for gpu-sharing in gke

- docker/Dockerfile.ubi
- docker/Dockerfile.ubuntu
In DCGM 4.0, packages are separated into multiple small packages.
The library needed for enable profiling module, libdcgmmoduleprofiling.so.4 is not included in package datacenter-gpu-manager-4-core, but in package gpu-manager-4-proprietary.
This fixes #449
> fix: install required packages for DCP metrics

- cmd/dcgm-exporter/main.go
- pkg/cmd/app.go
We introduce log formatting to support both text and json formats. This can be configured through a CLI flag "log-format" or env var "DCGM_EXPORTER_LOG_FORMAT".
Notably, the log format will capture any DCGM logging that is configured.
We also move the automaxprocs call from an unused import to be explicitly called when starting the dcgm exporter to ensure its logging format honors the configuration.
> feat: add log formatting

- deployment/templates/service.yaml
- deployment/values.yaml
This PR was created in response to the gpu-operator issue https://github.com/NVIDIA/gpu-operator/issues/1439
The OP of the GitHub issue would like to set the InternalTrafficPolicy as they have their own monitoring system running as a daemonset and they want to ensure that those pods only scrape the metrics from the dcgm-exporter pods in the same node
I wanted to raise a PR here to see if this change makes sense before making similar changes in gpu-operator
> [helm][k8s-service] add support for setting internalTrafficPolicy

- go.mod
- go.sum
- pkg/cmd/app.go
here we take advantage of all of the wiring in place to handle os signals, and send a hangup when the config file changes
tested locally running in docker
built with:
```
docker build . -f docker/Dockerfile.ubuntu -t newdcgm --build-arg "GOLANG_VERSION=1.23.0"
```
docker logs
```
»  docker run --privileged --rm -it --name "dcgm" newdcgm -f /etc/dcgm-exporter/dcp-metrics-included.csv
2025/04/10 22:45:41 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
2025/04/10 22:45:41 INFO Starting dcgm-exporter Version=4.2.0-4.1.0
2025/04/10 22:45:41 INFO Attempting to initialize DCGM.
2025/04/10 22:45:41 INFO Initialized DCGM Fields module.
2025/04/10 22:45:41 INFO DCGM successfully initialized!
2025/04/10 22:45:41 INFO Attempting to initialize NVML library.
2025/04/10 22:45:41 INFO NVML provider …
```
> feat(app): reload on config change

- deployment/templates/_helpers.tpl
- deployment/templates/daemonset.yaml
- deployment/templates/metrics-configmap.yaml
- deployment/templates/role.yaml
- deployment/templates/rolebinding.yaml
- deployment/templates/service-monitor.yaml
- deployment/templates/service.yaml
- deployment/templates/serviceaccount.yaml
- deployment/templates/tls-secret.yaml
- deployment/templates/web-config-configmap.yaml
Minor Helm chart improvements. Adds the charts labels to the metrics configmap and adds the label `app.kubernetes.io/component: dcgm-exporter` to the selector labels defined in _helpers.tpl to reduce duplication.
Example of what the labels/selector labels looks like with the changes
``` 
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: example-dcgm-exporter
namespace: example
labels:
helm.sh/chart: dcgm-exporter-4.1.1
app.kubernetes.io/name: dcgm-exporter
app.kubernetes.io/instance: example-dcgm-exporter
app.kubernetes.io/component: dcgm-exporter
app.kubernetes.io/version: "4.1.1"
app.kubernetes.io/managed-by: Helm
spec:
updateStrategy:
type: RollingUpdate
rollingUpdate:
maxUnavailable: 1
maxSurge: 0
selector:
matchLabels:
app.kubernetes.io/name: dcgm-exporter …
```
> chore: add labels to configmap and remove label duplication

- internal/pkg/integration_test/collector_test.go
- internal/pkg/integration_test/transformation_test.go
- internal/pkg/testutils/test_utils.go
- internal/pkg/transformation/kubernetes.go
- internal/pkg/transformation/kubernetes_test.go
Fixes https://github.com/NVIDIA/dcgm-exporter/issues/497
This is fixed by updating the `podresourcesapi` from `v1alpha1` to `v1`, as the former doesn't include native sidecar container (restartable initContainers) in the pod-resources response output.
Tested in EKS cluster with this fix, native sidecar container `DCGM_.*` metrics now contain the correct pod and namespace labels.
> Fix: update podresourcesapi from v1alpha1 to v1 to fix issue with native sidecar metrics labels

- deployment/templates/service-monitor.yaml
Hello,  
when installing from the main branch, I encountered the following error:  
```
Warning  InstallFailed     8s (x5 over 20s)  helm-controller  Helm install failed for release kube-system/nvdp-metrics with chart dcgm-exporter@4.1.2: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:  
line 36: mapping key "app.kubernetes.io/component" already defined at line 35
```
This commit removes the duplicate key.
> Fix duplicate key in Helm chart

- deployment/templates/clusterrole.yaml
- deployment/templates/clusterrolebinding.yaml
- deployment/templates/daemonset.yaml
- deployment/values.yaml
- internal/pkg/appconfig/types.go
- internal/pkg/transformation/kubernetes.go
- internal/pkg/transformation/kubernetes_test.go
- internal/pkg/transformation/types.go
- internal/pkg/utils/utils.go
- internal/pkg/utils/utils_test.go
- pkg/cmd/app.go
- tests/e2e/e2e_actions_test.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/internal/framework/kube.go
Adds opt-in Kubernetes pod label support to dcgm-exporter, enabling GPU metrics to be enriched with labels from pods using the resources. This allows tracking GPU usage by application, implementing chargeback, and debugging performance issues at the workload level.
We have been successfully running these changes in production since the end of December 2024, and it's long overdue that we share this back with the community.
Extends the existing `PodMapper` to fetch pod labels via the Kubernetes API and enrich GPU metrics with sanitized pod labels. Includes caching to minimize API server load.
* **Opt-in:** Disabled by default
* **Cached:** Prevents redundant API calls
* **RBAC integrated:** Conditional `ClusterRole`/`ClusterRoleBinding`
* **Backward compatible:** Existing metrics unchanged …
> Kubernetes Pod Label Support

- internal/pkg/transformation/hpc.go
I enabled the 'hpc-job-mapping-dir' parameter, which specifies the directory '/tmp/hpc_mapper_dir'. Under this directory, several GPU files will be generated. However, since some Gpus are idle and no tasks are running on them, the GPU files are empty. Here, the code only checks whether the file exists and does not check jobs. As a result, when the file exists but jobs are empty, it will enter if instead of loloop jobs, thus preventing the collection of idle GPU information
I have eight GPU cards
However, since two cards were idle and there was no job id, the gpu modification information was not reported
> fix(hpc ) Add a judgment on whether jobs is empty

- deployment/templates/clusterrole.yaml
- deployment/templates/clusterrolebinding.yaml
- deployment/templates/daemonset.yaml
- deployment/values.yaml
- internal/pkg/appconfig/types.go
- internal/pkg/transformation/const.go
- internal/pkg/transformation/kubernetes.go
- internal/pkg/transformation/kubernetes_test.go
- internal/pkg/transformation/types.go
- pkg/cmd/app.go
This commit adds an opt-in Kubernetes pod UID support to dcgm-exporter, enabling GPU metrics to be enriched with pod UID attributes from the pods that are using the resources. The implementation leverages the existing unified metadata caching system to minimize API server load and optimize performance.
**Key Changes:**
* Extended existing PodMapper with UID collection and caching capabilities
* Integrated pod UIDs into GPU metrics as `pod_uid` attribute
* Added `DCGM_EXPORTER_KUBERNETES_ENABLE_POD_UID` environment variable
* Unified metadata caching for both labels and UIDs with optimized API calls
* Comprehensive test coverage for UID functionality
The pod UID is automatically included in GPU metrics when the feature is enabled, providing better observability and correlation between …
> Kubernetes Pod UID Support

- internal/pkg/transformation/kubernetes.go
- internal/pkg/transformation/kubernetes_test.go
Fixes https://github.com/NVIDIA/dcgm-exporter/issues/549.
If pods are not scheduled and using the GPU resources, dcgm-exporter should still expose the underlying GPU metrics when either of these flags are enabled.
> fix: enable metrics without pods when using kubernetes-enable-{dra,virtual-gpus}

- internal/pkg/appconfig/types.go
- internal/pkg/nvmlprovider/provider.go
- internal/pkg/nvmlprovider/provider_test.go
- pkg/cmd/app.go
this PR adds the option to exit if we are unable to initialize the nvml provider. it has been observed and reported that nvml.Init() periodically fails to initialize the provider, but this error is currently ignored in dcgm-exporter. the result is an exporter that is unable to export gpu metrics, and in my case, exports nothing. the only indication that there has been an issue on startup is visible in the logs.
nvml init issue reported here https://github.com/NVIDIA/go-nvml/issues/164 and here https://github.com/NVIDIA/dcgm-exporter/issues/530
> feat(dcgm-exporter): add option to fail on nvml provider init error

- README.md
go.mod requires golang 1.24 but documentation still says 1.22
> Update README.md golang requirement

- internal/pkg/transformation/hpc.go
> Handle uninitialized map in HPC job mapping
